### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by aliflcat** [xf4j/brats17#6]
Traceback (most recent call last):
  File "/home/ubuntu/new/brats17-master/generate_patches.py", line 54, in <module>
    pool.map(batch_works, range(n_processes))
  File "/home/ubuntu/anaconda3/envs/py2/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/ubuntu/anaconda3/envs/py2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
IndexError: list index out of range

hello,when I run python bias_correction.py Brats17TrainingData,the error occured,can you tell me how to solve it?Many thanks!

**Comment by liujing1995** [comment]
hello guy ,i have the same question .Have you solved the question? thanks!

**Comment by ikramabdel** [comment]
Hello me too , anyone solve it ?
